### ISSUE TITLE
Invalid OreDict registration

### ISSUE THREAD

**Issue by ghost** [jadedcat/JadedTweaks#32]
---
- Invalid registration attempt for an Ore Dictionary item with name transposition has occurred. The registration has been denied to prevent crashes. The mod responsible for the registration needs to correct this.
-  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:491)
-  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:470)
-  at com.jadedpacks.jctweaks.helpers.OreDictionaryTweaks.init(OreDictionaryTweaks.java:27)
-  at com.jadedpacks.jctweaks.Main.init(Main.java:135)
-  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
-  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)...
  ****************************************

**Comment by ghost** [comment]
This issue was moved to JadedPacks/JadedTweaks#3
